### ISSUE TITLE
Unverified breakpoint in Angular application

### ISSUE THREAD

**Issue by thfsilvab** [firefox-devtools/vscode-firefox-debug#310]
After following some guides, I wasn't able to successfully debug my Angular application using Firefox Debugger. Breakpoints are grey and outlined with the message "Unverified Breakpoint", maybe I missed something?

**launch.json**
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Firefox: Launch",
      "request": "launch",
      "type": "firefox",
      "preLaunchTask": "serve",
      "postDebugTask": "kill",
      "url": "https://localhost.mydomain.com:4200/",
      "webRoot": "${workspaceFolder}",
      "reAttach": false,
      "pathMappings": [
        {
          "url": "webpack:///src/",
          "path": "${webRoot}/src/"
        }
      ]
    },
    {
      "name": "Edge: Launch",
      "request": "launch",
      "type": "msedge",
      "preLaunchTask": "serve",
      "postDebugTask": "kill",
      "url": "https://localhost.mydomain.com:4200/",
      "webRoot": "${workspaceFolder}",
    }
  ]
}
```

**tasks.json**
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "start",
      "isBackground": true,
      "problemMatcher": {
        "owner": "typescript",
        "pattern": "$tsc",
        "background": {
          "activeOnStart": true,
          "beginsPattern": {
            "regexp": "(.*?)"
          },
          "endsPattern": {
            "regexp": "bundle generation complete"
          }
        }
      }
    },
    {
      "type": "npm",
      "script": "test",
      "isBackground": true,
      "problemMatcher": {
        "owner": "typescript",
        "pattern": "$tsc",
        "background": {
          "activeOnStart": true,
          "beginsPattern": {
            "regexp": "(.*?)"
          },
          "endsPattern": {
            "regexp": "bundle generation complete"
          }
        }
      }
    },
    {
      "label": "serve",
      "isBackground": true,
      "command": "ng",
      "type": "shell",
      "presentation": {
        "reveal": "always"
      },
      "problemMatcher": {
        "owner": "typescript",
        "pattern": "$tsc",
        "fileLocation": "relative",
        "background": {
          "activeOnStart": true,
          "beginsPattern": {
            "regexp": "(.*?)"
          },
          "endsPattern": {
            "regexp": "bundle generation complete"
          }
        }
      },
      "args": [
        "serve",
        "--ssl",
        "--ssl-key",
        "C:\\mypath\\localhost.key",
        "--ssl-cert",
        "C:\\mypath\\localhost.crt",
        "--proxy-config",
        "proxy.json",
        "--port",
        "4200",
        "--host",
        "localhost.mydomain.com"
      ],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    },
    {
      "label": "kill",
      "command": "echo ${input:terminate}",
      "type": "shell",
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "terminate",
      "type": "command",
      "command": "workbench.action.tasks.terminate",
      "args": "terminateAll"
    }
  ]
}
```

Some possible errors that I checked and it's all fine:
- Same custom tasks work fine when debugging in Edge (configuration I use for Edge is in launch.json)
- `${workspaceFolder}` is pointing to the right path
- I tried overriding `pathMappings` because the debugger was also not working with the implicitly added `pathMappings`

I'm currently using Firefox 102.5.0esr (64-bit) on Windows 10.

**Comment by tom-wegener** [comment]
Hey, 
I have the same problem, did you find a fix for that problem?

**Comment by Trellmor** [comment]
Had the same problem. Looks like something changed with Node 18. Adding ̀```--host=127.0.0.1``` to ```ng serve``` fixed it for me. E.g.

```
ng serve --host=127.0.0.1
```

Also see this [StackOverflow post](https://stackoverflow.com/a/72792138/833893)

**Comment by thfsilvab** [comment]
Yes! I was recently able to fix it, thanks to ChatGPT LOL, I added `--source-map=true` to my `ng serve` command, which can also be configured through the angular.json file.

**Comment by crossan007** [comment]
Adding the `--host=127.0.0.1` to the `ng serve` command seems to have fixed the issue for me.

As mentioned in the [StackOverflow post](https://stackoverflow.com/a/72792138/833893) (mentioned above by @Trellmor); the problem began when I upgraded from Node 16 to Node 18.

Another observable symptom of this problem was the following message in my VSCode "Output" tab (selecting `Extension Host`):
```
2024-01-10 11:03:08.323 [error] Error: Invalid debug adapter
    at v.m (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1553:95)
    at v.$acceptDAExit (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1553:35)
    at m.S (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:18889)
    at m.Q (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:18655)
    at m.M (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:17748)
    at m.L (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:16966)
    at o.value (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1561:15630)
    at u.y (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at u.fire (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.fire (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:14449)
    at x.onmessage (vscode-file://vscode-app/c:/Users/Charles/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1657:7802)
```
