### ISSUE TITLE
Can not be installed

### ISSUE THREAD

**Issue by runxel** [firefox-devtools/vscode-firefox-debug#324]
MacBook Pro, MacOS 12.6.3
VSCode Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

Output log:
```log
[error] net::ERR_NAME_NOT_RESOLVED: Download: net::ERR_NAME_NOT_RESOLVED
    at yt.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:90:157025)
    at async X.x (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:20760)
    at async X.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:91:18897)
```

**Comment by nchevobbe** [comment]
is this still happening? How are you trying to install the extension?

**Comment by runxel** [comment]
Wow, one year later. I have no time to find out these days.
